### ISSUE TITLE
videorama = zerotube without webtorrent (join projects?)

### ISSUE THREAD

**Issue by haschimoto** [rllola/zeroTube#11]
Hi,

we work on a similar prototype like zerotube:
https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/

We dont use webtorrent though, still many things to do and make it look better like Zerotube :)

Are you good at python/zeronet programming and like to help coding?

**Comment by obv-mikhail** [comment]
ZeroNet sites can't use python. Where are the video files stored for your project?

**Comment by haschimoto** [comment]
Zeronet framework uses python, so certain functionality have to be programmed in the backend.
Files are stored on each users video channel zeronet site.

**Comment by rllola** [comment]
I am sorry but I already have a lot of work with my work and this project. But that look interesting, do you have a github with the source code ?

**Comment by obv-mikhail** [comment]
@rllola https://github.com/zer0net/videorama-central .

If files are stored in the site they are limited by 10mb per channel? WebTorrent approach seems better in this case. ZeroTube could benefit from channels as well though.

**Comment by rllola** [comment]
@obv-mikhail Yeah I have been trying to think of way to use the merger site feature for better performance. I need to take a look at it more in depth. I am going to test it in a new project.
