### ISSUE TITLE
support for ZeroVerse.bit

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [rllola/zeroTube#2]
Please add ZeroVerse.bit (1) which is another ID provider.
If you need reasons to add, see the why-section (2).

Here (3) is a howto for adding.

(1) http://127.0.0.1:43110/zeroverse.bit
(2) http://127.0.0.1:43110/zeroverse.bit/why.html
(3) section "III. how to allow ZeroVerse.bit users on my site?" at http://127.0.0.1:43110/zeroblog.bit/?Post:15:get+yourself+an+ID+@+ZeroVerse.bit

**Comment by rllola** [comment]
Hello,

I am missing time to do it and also I am still working on ZeroTube concept but when I will go live and have more time I will take a look at it.
