### ISSUE TITLE
Change license and allow people to continue this work

### ISSUE THREAD

**Issue by tyduptyler13** [rllola/zeroTube#21]
I would be interested in forking and continuing this project; but without a license, I can't reasonably do so.

**Comment by rllola** [comment]
Hello,

Yes I can do that

**Comment by tyduptyler13** [comment]
Hi, I simply need you to create a license on this library that permits further work on it.

Preferably not gpl or lgpl, I usually prefer to work on MIT, zlib, or BSD licensed software.

Thank your for responding quickly btw, I was wondering if you were still around.

**Comment by rllola** [comment]
Done !

Sorry for the delay. I am actually quite excited to see what it will become. I truly believe in this project purpose and I am really sad I haven't find more time to spend on this.

Have fun and keep me posted of your progress !

**Comment by tyduptyler13** [comment]
Sweet, thanks! I dig the license you chose. :p I don't think I've ever seen that one before but I can agree with it.
