### ISSUE TITLE
It needs something to run in ZeroNet?

### ISSUE THREAD

**Issue by danimesq** [rllola/zeroTube#22]

**Comment by rllola** [comment]
Hello,

No it doesn't need anything to run in zeronet. It is only using pure javscript and should be working in any modern browser. But there is currently no seeders for any videos...

**Comment by danimesq** [comment]
@rllola
http://127.0.0.1:43110/1FUQPLXHimgCvYHH7v3bJXspJ7bMBUXcEb is the address?
