### ISSUE TITLE
Merge with KopyKate Big?

### ISSUE THREAD

**Issue by danimesq** [rllola/zeroTube#24]

**Comment by danimesq** [comment]
@misses-robot

**Comment by rllola** [comment]
Hi,

I am actually going to modify zeroTube so it would work like mixtape. It will use BigFile feature and merger site feature. I am still experimenting in Mixtape. @misses-robot is doing great with KopyKate and maintain it. However I am open to collaborating on this so mergerSite could both work in KopyKate and zeroTube (but I am still not sure how).

**Comment by danimesq** [comment]
zeroTube could be a merger listing, showing first the original content.
