### ISSUE TITLE
Updating: 1 left error

### ISSUE THREAD

**Issue by Split7fire** [rllola/zeroTube#4]
data/zerotube_dev.db is missing.
I am the one, who catch this? :)

**Comment by rllola** [comment]
This should be fixed ?
The zerotube_dev.db file should actually not be uploaded but build from the json files. 

You can see the comment from nofishme in the reddit thread : 
https://www.reddit.com/r/zeronet/comments/4gpx9h/zerotube_it_is_alive/d2jwvs9

**Comment by Split7fire** [comment]
> This should be fixed ?

I think so :)

> The zerotube_dev.db file should actually not be uploaded but build from the json files.

But it isn't. I don't know why.
